version: "3"
services:
  bedrockconnect:
    image: bedrockconnect/bedrockconnect:latest
    restart: always
    ports:
      - "19132:19132/udp"
    environment:
      nodb: "true"
  bind9:
    build: 
      context: ./bind9
      args: 
        BCIP: 104.238.130.180
        NSIP: 104.238.130.180
    ports: 
      - "53:53/udp"
